export interface LanguageItem {
  code: string;
  name: string;
  flag?: string;
}

export const APP_LANGUAGES: LanguageItem[] = [
  { code: "en", name: "English" },
  { code: "bn", name: "Bengali" },
  { code: "ar", name: "Arabic" },
  { code: "ur", name: "Urdu" },
  { code: "id", name: "Indonesian" },
  { code: "tr", name: "Turkish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "es", name: "Spanish" },
  { code: "ru", name: "Russian" },
  { code: "fa", name: "Persian" },
  { code: "hi", name: "Hindi" },
  { code: "ms", name: "Malay" },
  { code: "pt", name: "Portuguese" },
  { code: "it", name: "Italian" },
  { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "sw", name: "Swahili" },
  { code: "ha", name: "Hausa" },
  { code: "so", name: "Somali" },
  { code: "nl", name: "Dutch" },
  { code: "sv", name: "Swedish" },
  { code: "no", name: "Norwegian" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "pl", name: "Polish" },
  { code: "ro", name: "Romanian" },
  { code: "hu", name: "Hungarian" },
  { code: "cs", name: "Czech" },
  { code: "el", name: "Greek" },
  { code: "uk", name: "Ukrainian" },
  { code: "vi", name: "Vietnamese" },
  { code: "th", name: "Thai" },
  { code: "tl", name: "Filipino (Tagalog)" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "ml", name: "Malayalam" },
  { code: "kn", name: "Kannada" },
  { code: "gu", name: "Gujarati" },
  { code: "mr", name: "Marathi" },
  { code: "pa", name: "Punjabi" },
  { code: "si", name: "Sinhalese" },
  { code: "my", name: "Burmese" },
  { code: "km", name: "Khmer" },
  { code: "am", name: "Amharic" },
  { code: "az", name: "Azerbaijani" },
  { code: "uz", name: "Uzbek" },
  { code: "kk", name: "Kazakh" },
  { code: "ky", name: "Kyrgyz" },
  { code: "tg", name: "Tajik" },
  { code: "ps", name: "Pashto" },
  { code: "ku", name: "Kurdish" },
  { code: "sq", name: "Albanian" },
  { code: "bs", name: "Bosnian" },
  { code: "hr", name: "Croatian" },
  { code: "sr", name: "Serbian" },
  { code: "bg", name: "Bulgarian" },
  { code: "mk", name: "Macedonian" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "lt", name: "Lithuanian" },
  { code: "lv", name: "Latvian" },
  { code: "et", name: "Estonian" },
  { code: "is", name: "Icelandic" },
  { code: "ga", name: "Irish" },
  { code: "cy", name: "Welsh" },
  { code: "mt", name: "Maltese" },
  { code: "af", name: "Afrikaans" },
  { code: "zu", name: "Zulu" },
  { code: "xh", name: "Xhosa" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona" },
  { code: "ny", name: "Chichewa" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "mg", name: "Malagasy" },
  { code: "yo", name: "Yoruba" },
  { code: "ig", name: "Igbo" },
  { code: "om", name: "Oromo" },
  { code: "ti", name: "Tigrinya" },
  { code: "ne", name: "Nepali" },
  { code: "as", name: "Assamese" },
  { code: "or", name: "Odia" },
  { code: "sd", name: "Sindhi" },
  { code: "ug", name: "Uyghur" },
  { code: "mn", name: "Mongolian" },
  { code: "hy", name: "Armenian" },
  { code: "ka", name: "Georgian" },
  { code: "he", name: "Hebrew" },
  { code: "yi", name: "Yiddish" },
  { code: "la", name: "Latin" },
  { code: "eo", name: "Esperanto" },
  { code: "eu", name: "Basque" },
  { code: "gl", name: "Galician" },
  { code: "ca", name: "Catalan" },
  { code: "lb", name: "Luxembourgish" },
  { code: "fy", name: "Frisian" },
  { code: "ht", name: "Haitian Creole" },
  { code: "jv", name: "Javanese" },
  { code: "su", name: "Sundanese" },
  { code: "ceb", name: "Cebuano" },
  { code: "hmn", name: "Hmong" },
  { code: "sm", name: "Samoan" },
  { code: "haw", name: "Hawaiian" },
  { code: "co", name: "Corsican" }
];
